[font]

size = 14
  [font.normal]
  family = "JetBrainsMono Nerd Font"

[window]
  option_as_alt = "Both"

[shell]
program = "/opt/homebrew/bin/fish"
args = [ "--login" ]

#
# [colors.primary]
# background = '#000000'


# # TokyoNight Alacritty Colors
#
# # Default colors
# [colors.primary]
# background = '#1a1b26'
# foreground = '#c0caf5'
#
# #[colors.cursor]
# #cursor = '#c0caf5'
# #text = '#1a1b26'
#
# # Normal colors
# [colors.normal]
# black = '#15161e'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'
#
# # Bright colors
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#ff9e64'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#db4b4b'

# Cyberpunk-Neon colours
# [colors.primary]
# background = '0x000b1e'
# foreground = '0x0abdc6'
#
# # Uncomment the following block if you want to specify cursor colors
# # [colors.cursor]
# # text = '0x2e2e2d'
# # cursor = '0xffffff'
#
# [colors.normal]
# black = '0x123e7c'
# red = '0xff0000'
# green = '0xd300c4'
# yellow = '0xf57800'
# blue = '0x123e7c'
# magenta = '0x711c91'
# cyan = '0x0abdc6'
# white = '0xd7d7d5'
#
# [colors.bright]
# black = '0x1c61c2'
# red = '0xff0000'
# green = '0xd300c4'
# yellow = '0xf57800'
# blue = '0x00ff00'
# magenta = '0x711c91'
# cyan = '0x0abdc6'
# white = '0xd7d7d5'
#
# [colors.dim]
# black = '0x1c61c2'
# red = '0xff0000'
# green = '0xd300c4'
# yellow = '0xf57800'
# blue = '0x123e7c'
# magenta = '0x711c91'
# cyan = '0x0abdc6'
# white = '0xd7d7d5'
